version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

# get topic list
# kafka-topics.sh --list --bootstrap-server localhost:9092

# create topic
# kafka-topics.sh --create --topic event_topic --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1

# publish topic
# bin/kafka-console-producer.sh --broker-list localhost:9092 --topic action_topic

# subscribe topic
# kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic event_topic --from-beginning