spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  jpa:
    hibernate:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.Mysql8Dialect
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        ddl-auto: create-drop
        default_batch_fetch_size: 1000